name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'corretto'
        cache: maven
        
    - name: Test with Maven
      run: mvn -B clean test --file ./FoodRescue/pom.xml

    # The test reports are generated in target/surefire-reports
    - name: Collect Test Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: TestReport
        path: ./FoodRescue/target/surefire-reports
        retention-days: 30
